### ISSUE TITLE
Add-these-movies

### ISSUE THREAD

**Issue by SrilalS** [Shafran123/movie_mania#16]
https://www.imdb.com/title/tt0499549/            
"title": "Avatar",
            "type": "Movie",
            "year": "2009",
            "tag_1" : "Action",
            "tag_2" : "Adventure",

https://www.imdb.com/title/tt0133093/
 "title": "The Matrix",
            "type": "Movie",
            "year": "1999",
            "tag_1" : "Action",
            "tag_2" : "Adventure",

**Comment by zirmax** [comment]
Hey, would like to work on this ;)
