### ISSUE TITLE
Center Movie List 

### ISSUE THREAD

**Issue by Shafran123** [Shafran123/movie_mania#4]
Align Center the fetched movie list

**Comment by chauhanparth210** [comment]
Hello @Shafran123 , I want to contribute and if you don't mind can I picking this issue?

**Comment by Shafran123** [comment]
yep

**Comment by chauhanparth210** [comment]
@Shafran123 sir, is there mistake I made?

**Comment by Shafran123** [comment]
you have edited different file.but did correctly centering the movie list!
